# Generated by Django 2.2.8 on 2020-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_jobframecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bulk_label',
            field=models.BooleanField(default=True),
        ),
    ]
